/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as PolitykaCookiesRouteImport } from './routes/polityka-cookies'
import { Route as PakietyRouteImport } from './routes/pakiety'
import { Route as OgDebugRouteImport } from './routes/og-debug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutFailedRouteImport } from './routes/checkout.failed'
import { Route as CheckoutCanceledRouteImport } from './routes/checkout.canceled'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DSlugIndexRouteImport } from './routes/d.$slug.index'
import { Route as AuthenticatedDoradcaIndexRouteImport } from './routes/_authenticated/doradca/index'
import { Route as DSlugAktywujRouteImport } from './routes/d.$slug_.aktywuj'
import { Route as DSlugOfertaRouteImport } from './routes/d.$slug.oferta'
import { Route as DSlugKontaktRouteImport } from './routes/d.$slug.kontakt'
import { Route as ApiPublicOgDebugRouteImport } from './routes/api/public/og-debug'
import { Route as ApiPublicMetaCapiRouteImport } from './routes/api/public/meta-capi'
import { Route as AuthenticatedDoradcaNoweRouteImport } from './routes/_authenticated/doradca/nowe'
import { Route as AuthenticatedAdminZamowieniaRouteImport } from './routes/_authenticated/admin/zamowienia'
import { Route as AuthenticatedAdminGscStatusRouteImport } from './routes/_authenticated/admin/gsc-status'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicDemosExpireRouteImport } from './routes/api/public/demos/expire'
import { Route as AuthenticatedDoradcaDemoDemoIdRouteImport } from './routes/_authenticated/doradca/demo.$demoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaCookiesRoute = PolitykaCookiesRouteImport.update({
  id: '/polityka-cookies',
  path: '/polityka-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PakietyRoute = PakietyRouteImport.update({
  id: '/pakiety',
  path: '/pakiety',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDebugRoute = OgDebugRouteImport.update({
  id: '/og-debug',
  path: '/og-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutFailedRoute = CheckoutFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCanceledRoute = CheckoutCanceledRouteImport.update({
  id: '/canceled',
  path: '/canceled',
  getParentRoute: () => CheckoutRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const DSlugIndexRoute = DSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DSlugRoute,
} as any)
const AuthenticatedDoradcaIndexRoute =
  AuthenticatedDoradcaIndexRouteImport.update({
    id: '/doradca/',
    path: '/doradca/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DSlugAktywujRoute = DSlugAktywujRouteImport.update({
  id: '/d/$slug_/aktywuj',
  path: '/d/$slug/aktywuj',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugOfertaRoute = DSlugOfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => DSlugRoute,
} as any)
const DSlugKontaktRoute = DSlugKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => DSlugRoute,
} as any)
const ApiPublicOgDebugRoute = ApiPublicOgDebugRouteImport.update({
  id: '/api/public/og-debug',
  path: '/api/public/og-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaCapiRoute = ApiPublicMetaCapiRouteImport.update({
  id: '/api/public/meta-capi',
  path: '/api/public/meta-capi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoradcaNoweRoute =
  AuthenticatedDoradcaNoweRouteImport.update({
    id: '/doradca/nowe',
    path: '/doradca/nowe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminZamowieniaRoute =
  AuthenticatedAdminZamowieniaRouteImport.update({
    id: '/admin/zamowienia',
    path: '/admin/zamowienia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGscStatusRoute =
  AuthenticatedAdminGscStatusRouteImport.update({
    id: '/admin/gsc-status',
    path: '/admin/gsc-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDemosExpireRoute = ApiPublicDemosExpireRouteImport.update({
  id: '/api/public/demos/expire',
  path: '/api/public/demos/expire',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoradcaDemoDemoIdRoute =
  AuthenticatedDoradcaDemoDemoIdRouteImport.update({
    id: '/doradca/demo/$demoId',
    path: '/doradca/demo/$demoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/brief': typeof BriefRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/og-debug': typeof OgDebugRoute
  '/pakiety': typeof PakietyRoute
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/canceled': typeof CheckoutCanceledRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/admin/gsc-status': typeof AuthenticatedAdminGscStatusRoute
  '/admin/zamowienia': typeof AuthenticatedAdminZamowieniaRoute
  '/doradca/nowe': typeof AuthenticatedDoradcaNoweRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/og-debug': typeof ApiPublicOgDebugRoute
  '/d/$slug/kontakt': typeof DSlugKontaktRoute
  '/d/$slug/oferta': typeof DSlugOfertaRoute
  '/d/$slug/aktywuj': typeof DSlugAktywujRoute
  '/doradca/': typeof AuthenticatedDoradcaIndexRoute
  '/d/$slug/': typeof DSlugIndexRoute
  '/doradca/demo/$demoId': typeof AuthenticatedDoradcaDemoDemoIdRoute
  '/api/public/demos/expire': typeof ApiPublicDemosExpireRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/brief': typeof BriefRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/og-debug': typeof OgDebugRoute
  '/pakiety': typeof PakietyRoute
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/canceled': typeof CheckoutCanceledRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/gsc-status': typeof AuthenticatedAdminGscStatusRoute
  '/admin/zamowienia': typeof AuthenticatedAdminZamowieniaRoute
  '/doradca/nowe': typeof AuthenticatedDoradcaNoweRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/og-debug': typeof ApiPublicOgDebugRoute
  '/d/$slug/kontakt': typeof DSlugKontaktRoute
  '/d/$slug/oferta': typeof DSlugOfertaRoute
  '/d/$slug/aktywuj': typeof DSlugAktywujRoute
  '/doradca': typeof AuthenticatedDoradcaIndexRoute
  '/d/$slug': typeof DSlugIndexRoute
  '/doradca/demo/$demoId': typeof AuthenticatedDoradcaDemoDemoIdRoute
  '/api/public/demos/expire': typeof ApiPublicDemosExpireRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/brief': typeof BriefRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/og-debug': typeof OgDebugRoute
  '/pakiety': typeof PakietyRoute
  '/polityka-cookies': typeof PolitykaCookiesRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/canceled': typeof CheckoutCanceledRoute
  '/checkout/failed': typeof CheckoutFailedRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/d/$slug': typeof DSlugRouteWithChildren
  '/_authenticated/admin/gsc-status': typeof AuthenticatedAdminGscStatusRoute
  '/_authenticated/admin/zamowienia': typeof AuthenticatedAdminZamowieniaRoute
  '/_authenticated/doradca/nowe': typeof AuthenticatedDoradcaNoweRoute
  '/api/public/meta-capi': typeof ApiPublicMetaCapiRoute
  '/api/public/og-debug': typeof ApiPublicOgDebugRoute
  '/d/$slug/kontakt': typeof DSlugKontaktRoute
  '/d/$slug/oferta': typeof DSlugOfertaRoute
  '/d/$slug_/aktywuj': typeof DSlugAktywujRoute
  '/_authenticated/doradca/': typeof AuthenticatedDoradcaIndexRoute
  '/d/$slug/': typeof DSlugIndexRoute
  '/_authenticated/doradca/demo/$demoId': typeof AuthenticatedDoradcaDemoDemoIdRoute
  '/api/public/demos/expire': typeof ApiPublicDemosExpireRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/brief'
    | '/checkout'
    | '/login'
    | '/og-debug'
    | '/pakiety'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/checkout/canceled'
    | '/checkout/failed'
    | '/checkout/return'
    | '/d/$slug'
    | '/admin/gsc-status'
    | '/admin/zamowienia'
    | '/doradca/nowe'
    | '/api/public/meta-capi'
    | '/api/public/og-debug'
    | '/d/$slug/kontakt'
    | '/d/$slug/oferta'
    | '/d/$slug/aktywuj'
    | '/doradca/'
    | '/d/$slug/'
    | '/doradca/demo/$demoId'
    | '/api/public/demos/expire'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/brief'
    | '/checkout'
    | '/login'
    | '/og-debug'
    | '/pakiety'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/checkout/canceled'
    | '/checkout/failed'
    | '/checkout/return'
    | '/admin/gsc-status'
    | '/admin/zamowienia'
    | '/doradca/nowe'
    | '/api/public/meta-capi'
    | '/api/public/og-debug'
    | '/d/$slug/kontakt'
    | '/d/$slug/oferta'
    | '/d/$slug/aktywuj'
    | '/doradca'
    | '/d/$slug'
    | '/doradca/demo/$demoId'
    | '/api/public/demos/expire'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/brief'
    | '/checkout'
    | '/login'
    | '/og-debug'
    | '/pakiety'
    | '/polityka-cookies'
    | '/polityka-prywatnosci'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/checkout/canceled'
    | '/checkout/failed'
    | '/checkout/return'
    | '/d/$slug'
    | '/_authenticated/admin/gsc-status'
    | '/_authenticated/admin/zamowienia'
    | '/_authenticated/doradca/nowe'
    | '/api/public/meta-capi'
    | '/api/public/og-debug'
    | '/d/$slug/kontakt'
    | '/d/$slug/oferta'
    | '/d/$slug_/aktywuj'
    | '/_authenticated/doradca/'
    | '/d/$slug/'
    | '/_authenticated/doradca/demo/$demoId'
    | '/api/public/demos/expire'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BriefRoute: typeof BriefRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  OgDebugRoute: typeof OgDebugRoute
  PakietyRoute: typeof PakietyRoute
  PolitykaCookiesRoute: typeof PolitykaCookiesRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DSlugRoute: typeof DSlugRouteWithChildren
  ApiPublicMetaCapiRoute: typeof ApiPublicMetaCapiRoute
  ApiPublicOgDebugRoute: typeof ApiPublicOgDebugRoute
  DSlugAktywujRoute: typeof DSlugAktywujRoute
  ApiPublicDemosExpireRoute: typeof ApiPublicDemosExpireRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-cookies': {
      id: '/polityka-cookies'
      path: '/polityka-cookies'
      fullPath: '/polityka-cookies'
      preLoaderRoute: typeof PolitykaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakiety': {
      id: '/pakiety'
      path: '/pakiety'
      fullPath: '/pakiety'
      preLoaderRoute: typeof PakietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-debug': {
      id: '/og-debug'
      path: '/og-debug'
      fullPath: '/og-debug'
      preLoaderRoute: typeof OgDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/failed': {
      id: '/checkout/failed'
      path: '/failed'
      fullPath: '/checkout/failed'
      preLoaderRoute: typeof CheckoutFailedRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/canceled': {
      id: '/checkout/canceled'
      path: '/canceled'
      fullPath: '/checkout/canceled'
      preLoaderRoute: typeof CheckoutCanceledRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/d/$slug/': {
      id: '/d/$slug/'
      path: '/'
      fullPath: '/d/$slug/'
      preLoaderRoute: typeof DSlugIndexRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/_authenticated/doradca/': {
      id: '/_authenticated/doradca/'
      path: '/doradca'
      fullPath: '/doradca/'
      preLoaderRoute: typeof AuthenticatedDoradcaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/d/$slug_/aktywuj': {
      id: '/d/$slug_/aktywuj'
      path: '/d/$slug/aktywuj'
      fullPath: '/d/$slug/aktywuj'
      preLoaderRoute: typeof DSlugAktywujRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug/oferta': {
      id: '/d/$slug/oferta'
      path: '/oferta'
      fullPath: '/d/$slug/oferta'
      preLoaderRoute: typeof DSlugOfertaRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/d/$slug/kontakt': {
      id: '/d/$slug/kontakt'
      path: '/kontakt'
      fullPath: '/d/$slug/kontakt'
      preLoaderRoute: typeof DSlugKontaktRouteImport
      parentRoute: typeof DSlugRoute
    }
    '/api/public/og-debug': {
      id: '/api/public/og-debug'
      path: '/api/public/og-debug'
      fullPath: '/api/public/og-debug'
      preLoaderRoute: typeof ApiPublicOgDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-capi': {
      id: '/api/public/meta-capi'
      path: '/api/public/meta-capi'
      fullPath: '/api/public/meta-capi'
      preLoaderRoute: typeof ApiPublicMetaCapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doradca/nowe': {
      id: '/_authenticated/doradca/nowe'
      path: '/doradca/nowe'
      fullPath: '/doradca/nowe'
      preLoaderRoute: typeof AuthenticatedDoradcaNoweRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/zamowienia': {
      id: '/_authenticated/admin/zamowienia'
      path: '/admin/zamowienia'
      fullPath: '/admin/zamowienia'
      preLoaderRoute: typeof AuthenticatedAdminZamowieniaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/gsc-status': {
      id: '/_authenticated/admin/gsc-status'
      path: '/admin/gsc-status'
      fullPath: '/admin/gsc-status'
      preLoaderRoute: typeof AuthenticatedAdminGscStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demos/expire': {
      id: '/api/public/demos/expire'
      path: '/api/public/demos/expire'
      fullPath: '/api/public/demos/expire'
      preLoaderRoute: typeof ApiPublicDemosExpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doradca/demo/$demoId': {
      id: '/_authenticated/doradca/demo/$demoId'
      path: '/doradca/demo/$demoId'
      fullPath: '/doradca/demo/$demoId'
      preLoaderRoute: typeof AuthenticatedDoradcaDemoDemoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminGscStatusRoute: typeof AuthenticatedAdminGscStatusRoute
  AuthenticatedAdminZamowieniaRoute: typeof AuthenticatedAdminZamowieniaRoute
  AuthenticatedDoradcaNoweRoute: typeof AuthenticatedDoradcaNoweRoute
  AuthenticatedDoradcaIndexRoute: typeof AuthenticatedDoradcaIndexRoute
  AuthenticatedDoradcaDemoDemoIdRoute: typeof AuthenticatedDoradcaDemoDemoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminGscStatusRoute: AuthenticatedAdminGscStatusRoute,
  AuthenticatedAdminZamowieniaRoute: AuthenticatedAdminZamowieniaRoute,
  AuthenticatedDoradcaNoweRoute: AuthenticatedDoradcaNoweRoute,
  AuthenticatedDoradcaIndexRoute: AuthenticatedDoradcaIndexRoute,
  AuthenticatedDoradcaDemoDemoIdRoute: AuthenticatedDoradcaDemoDemoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCanceledRoute: typeof CheckoutCanceledRoute
  CheckoutFailedRoute: typeof CheckoutFailedRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCanceledRoute: CheckoutCanceledRoute,
  CheckoutFailedRoute: CheckoutFailedRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface DSlugRouteChildren {
  DSlugKontaktRoute: typeof DSlugKontaktRoute
  DSlugOfertaRoute: typeof DSlugOfertaRoute
  DSlugIndexRoute: typeof DSlugIndexRoute
}

const DSlugRouteChildren: DSlugRouteChildren = {
  DSlugKontaktRoute: DSlugKontaktRoute,
  DSlugOfertaRoute: DSlugOfertaRoute,
  DSlugIndexRoute: DSlugIndexRoute,
}

const DSlugRouteWithChildren = DSlugRoute._addFileChildren(DSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BriefRoute: BriefRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  OgDebugRoute: OgDebugRoute,
  PakietyRoute: PakietyRoute,
  PolitykaCookiesRoute: PolitykaCookiesRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DSlugRoute: DSlugRouteWithChildren,
  ApiPublicMetaCapiRoute: ApiPublicMetaCapiRoute,
  ApiPublicOgDebugRoute: ApiPublicOgDebugRoute,
  DSlugAktywujRoute: DSlugAktywujRoute,
  ApiPublicDemosExpireRoute: ApiPublicDemosExpireRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
